config/routes.rb
Rails.application.routes.draw do
  # new,index,edit,update,show,destroy,create

  #items routing(resources)
  # index,create -> ~/items
  # new -> ~/items/new
  # show,update,destroy -> ~/item/:id
  # edit -> ~/item/:id/edit

  root to: 'public/homes#top'
  get '/about'=>'public/homes#about'
  #get '/customers/sign_up'=>'customers#new'
  #resources :registrations,only:[:create]
  #delete '/customers/sign_out'=>'cusutomers#destroy'

  namespace :admin do
    resources :items
    resources :customers,except:[:new,:create,:destroy]
    resources :orders,only:[:show]
    get 'homes/top'
    delete '/admin/sign_out'=>'sessions#destroy'
  end

  scope module: :public do
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all'
    get '/customers/information/edit'=>'customers#edit',as:'customers_edit'
    get '/customers'=>'customers#show'
    patch '/customers/introduction'=>'customers#update'
    get '/customers/confirm'=>'customers#confirm'
    patch '/customers/withdrawal'=>'customers#withdrawal'
    post '/orders/check'=>'orders#check'
    get '/orders/complete'=>'orders#complete'
    resources :cart_items,except:[:new,:show,:edit]
    resources :orders,except:[:edit,:update,:destroy]
    resources :items,only:[:show,:index]
    resources :customer,oniy:[:show,:edit,:update,:confirm,:withdrawal]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
      has_one_attached :image
      has_many :cart_items
      has_many :order_products
 def  get_profile_image(width, height)
      
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed 
 end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
     @items = Item.all
  end

  def new
    @item=Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to  admin_item_path(@item.id)

  if @item.save
  end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    flash[:notice] = "successfully "
    redirect_to admin_item_path(@item.id)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:image, :name,:introduction,:price,:id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>

<%= form_with model:@item,url:admin_item_path(@item.id), method: :patch do |f| %>
<table>
  <tr>
  <td>商品画像</td>
  <td><%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %></td>
  </tr>

  <tr>
    <td>商品名</td>
    <td> <%= f.text_field :name%></td>
  </tr>

  <tr>
    <td>商品説明</td>
    <td> <%= f.text_field :introduction%></td>
  </tr>

  <tr>
    <td> 税抜価格</td>
    <td> <%= f.number_field :price%></td>
  </tr>
</table>
<%= f.submit '変更を保存',class: "btn btn-success"  %>
<% end %>

app/views/admin/items/index.html.erb
商品一覧  <%= link_to new_admin_item_path do %>

 <div><i class="fas fa-plus-circle fa-lg"></i></div>
<% end %>


<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <table>
            <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
            </tr>
            </thead>
           <tbody>
            <% @items.each do |item| %>
            <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name,edit_admin_item_path(item.id) %></td>
            <td><%= item.price %></td>
            </tr>
            <% end %>
           </tbody>
        </table>
</main>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model:@item,url:admin_items_path, method: :post do |f| %>
<table>
  <tr>
  <td>商品画像</td>
  <td><%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %></td>
  </tr>

  <tr>
    <td>商品名</td>
    <td> <%= f.text_field :name%></td>
  </tr>

  <tr>
    <td>商品説明</td>
    <td> <%= f.text_field :introduction%></td>
  </tr>

  <tr>
    <td> 税抜価格</td>
    <td> <%= f.number_field :price%></td>
  </tr>
</table>
<%= f.submit '新規登録',class: "btn btn-success"  %>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>

<table>
<tr>
    <%= image_tag @item.get_profile_image(100,100) %>
</tr>
  <tr> 
  <td>商品名</td>
  <td><%= @item.name %></td>
  </tr>
  
  <tr>
    <td>商品説明</td>
  　<td><%= @item.introduction %></td>
  </tr>
  
   <tr>
     <td>税込価格<br>(税抜価格)</td>
     <td><%= @item.price %></td>
   </tr>
</table>

<%= button_to "編集する" ,edit_admin_item_path(@item.id),method: :get,class:"btn btn-sm btn-success" %>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>