config/routes.rb
Rails.application.routes.draw do
  # new,index,edit,update,show,destroy,create

  #items routing(resources)
  # index,create -> ~/items
  # new -> ~/items/new
  # show,update,destroy -> ~/item/:id
  # edit -> ~/item/:id/edit

  root to: 'public/homes#top'
  get '/about'=>'public/homes#about'
  #get '/customers/sign_up'=>'customers#new'
  #resources :registrations,only:[:create]
  #delete '/customers/sign_out'=>'cusutomers#destroy'

  namespace :admin do
    resources :items
    resources :customers,except:[:new,:create,:destroy]
    resources :orders,only:[:show]
    get 'homes/top'
    delete '/admin/sign_out'=>'sessions#destroy'
  end

  scope module: :public do
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all'
    get '/customers/information/edit'=>'customers#edit',as:'customers_edit'
    get '/customers'=>'customers#show'
    patch '/customers/introduction'=>'customers#update'
    get '/customers/confirm'=>'customers#confirm'
    patch '/customers/withdrawal'=>'customers#withdrawal'
    post '/orders/check'=>'orders#check'
    get '/orders/complete'=>'orders#complete'
    resources :cart_items,except:[:new,:show,:edit]
    resources :orders,except:[:edit,:update,:destroy]
    resources :items,only:[:show,:index]
    resources :customer,oniy:[:show,:edit,:update,:confirm,:withdrawal]
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
     @customer = Customer.all.page(params[:page]).per(20)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer.id)
  end

  def customer_params
     params.require(:customer).permit(:last_name, :first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h1>
<%= form_with model:@customer,url:admin_customer_path, method: :patch do |f| %>
<table>
  <tr>
  <td>会員ID</td>
  <td><%= @customer.id %></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
  </tr>

  <tr>
    <td>フリガナ</td>
    <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
  </tr>

  <tr>
    <td>郵便番号</td>
    <td><%= f.text_field :postal_code %></td>
  </tr>

  <tr>
    <td>住所</td>
    <td><%= f.text_field :address %></td>
  </tr>

  <tr>
    <td>電話番号</td>
    <td><%= f.text_field :telephone_number %></td>
  </tr>

  <tr>
    <td>メールアドレス</td>
    <td><%= f.text_field :email %></td>
  </tr>

  <tr>
    <td>会員ステータス</td>
    <td><%= f.radio_button(:is_deleted, false) %>有効
        <%= f.radio_button(:is_deleted, true) %>退会
    </td>
  </tr>
</table>

<%= f.submit"変更を保存",class: "btn btn-success" %>
<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>

<table>
  <thead>
    <tr>
      会員ID
      氏名
      メールアドレス
      ステータス
  </thead>
  <tbody>
      <% @customer.each do |customer| %>
      <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.last_name,admin_customer_path(customer.id)%><%= link_to customer.first_name,admin_customer_path(customer.id) %></td>
      <td><%= customer.email %></td>

      <td><% if customer.is_deleted==false %>
      <p>有効</p>
      <% else %>
      <p>無効</p>
      <% end %>
    　</td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>

<table>
  <tr>
   <td>会員ID</td>
   <td><%= @customer.id %></td>
  </tr>

   <tr>
    <td>氏名</td>
    <td><%= @customer.first_name %><%= @customer.last_name %></td>
   </tr>

    <tr>
     <td>フリガナ</td>
     <td><%= @customer.last_name_kana%><%= @customer.first_name_kana %></td>
    </tr>

     <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
     </tr>

      <tr>
       <td>住所</td>
       <td><%= @customer.address %></td>
      </tr>

      <tr>
       <td>電話番号</td>
       <td><%= @customer.telephone_number %></td>
      </tr>

       <tr>＃＃
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
       </tr>
</table>

<%= button_to "編集する",edit_admin_customer_path,method: :get %>
<%= button_to "注文履歴一覧を見る", admin_homes_top_path,method: :get %>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>